[base]
# debug, info, error, and fatal
logLevel = 'debug'
weatherToken = ""

[jwt]
secret = ""
expiresIn = 604800 # 7 * 24 * 60 * 60 (expires in 7 Day)

[database]
protocol = "mysql"
host = "127.0.0.1"
port = "3306"
user = ""
password = ""
dbName = ""
logging = false
autoReconnect = true
ormEnable = true
  [database.dialectOptions]
  connectTimeout = 3000

  [database.pool]
  max = 100